apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: citricloud-webmail
resources:
  - namespace.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - webmail-deployment.yaml
  - webmail-service.yaml
  - webmail-ingress.yaml
