apiVersion: v1
kind: Service
metadata:
  name: citricloud-webmail
  namespace: citricloud-webmail
  labels:
    app.kubernetes.io/name: citricloud-webmail
    app.kubernetes.io/part-of: citricloud-webmail
spec:
  selector:
    app: citricloud-webmail
  ports:
    - name: http
      port: 80
      targetPort: http