apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "citricloud-webmail.fullname" . }}-redis
  labels:
    {{- include "citricloud-webmail.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "citricloud-webmail.fullname" . }}-redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "citricloud-webmail.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "citricloud-webmail.fullname" . }}-redis
        {{- include "citricloud-webmail.labels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "citricloud-webmail.fullname" . }}-secrets
                  key: REDIS_PASSWORD
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.redis.storageSize }}