apiVersion: v1
kind: Secret
metadata:
  name: {{ include "citricloud-webmail.fullname" . }}-secrets
  labels:
    {{- include "citricloud-webmail.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_ENCRYPTION_KEY: {{ required "secrets.sessionEncryptionKey is required" .Values.secrets.sessionEncryptionKey | quote }}
  REDIS_PASSWORD: {{ required "secrets.redisPassword is required" .Values.secrets.redisPassword | quote }}
  REDIS_URL: {{ printf "redis://:%s@%s-redis:6379" .Values.secrets.redisPassword (include "citricloud-webmail.fullname" .) | quote }}
  MAIL_PRESETS_JSON: {{ required "secrets.mailPresetsJson is required" .Values.secrets.mailPresetsJson | quote }}