apiVersion: v1
kind: Service
metadata:
  name: {{ include "citricloud-webmail.fullname" . }}
  labels:
    {{- include "citricloud-webmail.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "citricloud-webmail.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http